### ISSUE TITLE
Infinite loading problem already existing addon

### ISSUE THREAD

**Issue by ApekByz** [Leeous/gmod-addon-tool#14]
Hello sorry to bother you but I still have the problem in version 2.1 I use the addon which works perfectly, but I still have an infinite load, I tried to restore settings, uninstall, reinstall and with both versions (portable and install) it does not work.
![94994447-ef6c8800-0597-11eb-8e59-44249c5649b5](https://user-images.githubusercontent.com/43790127/95780882-09f7dd00-0ccd-11eb-9894-13ae7ca18c08.png)
Here are the logs:

```
--- Beginning of log --- 
[20:50]Garry's Mod Workshop Publisher 1.2
[20:50]
[20:50][Compiled May  8 2020 - 14:31:20]
[20:50]
[20:50]	2034776262	34.9 MB	"Kaep Gmod server contents addon #2"
[20:50]Getting published files..
[20:50]	2034758262	598.1 MB	"Kaep Gmod server contents addon #1"
[20:50]
[20:50]Done.
-----------------------
[20:53]Garry's Mod Workshop Publisher 1.2
[20:53][Compiled May  8 2020 - 14:31:20]
[20:53]
[20:53]Getting published files..
[20:53]	2034776262	34.9 MB	"Kaep Gmod server contents addon #2"
[20:53]	2034758262	598.1 MB	"Kaep Gmod server contents addon #1"
[20:53]
[20:53]Done.
[20:53]
```

**Comment by Leeous** [comment]
Could you possibly also include either a screenshot or copy & paste of the Chrome console? You can open it with `Ctrl` + `Shift` + `i` while GMAT is open. We will figure this out one way or another.

**Comment by ApekByz** [comment]
![Uploading image.png…]()

**Comment by ApekByz** [comment]
![image](https://user-images.githubusercontent.com/43790127/95793697-6e736600-0ce6-11eb-8c27-d6bef7ac23a0.png)

**Comment by Leeous** [comment]
@ApekByz that's very weird. That error is unrelated, so there must be something wrong with the logic of my app.
![image](https://user-images.githubusercontent.com/6354807/95888928-be3a4780-0d4f-11eb-8c5d-aa83557069ee.png)
[Here](https://drive.google.com/file/d/1Sc3PXEZsP_4wsHMTPGTnb8wQEzVOov-Q/view?usp=sharing) is a custom build of GMAT (had to upload it to my Google Drive because of GitHub's comment file size limits) that adds more detailed logging so I can get a good idea of what's going on, please try it out and send both the console output and the Chrome log. My only guess at the moment is `sendAPIRequest()` messing up the API request for whatever reason.

**Comment by ApekByz** [comment]
--- Beginning of log --- 

[20:4]Garry's Mod Workshop Publisher 1.2
[20:4][Compiled May  8 2020 - 14:31:20]
[20:4]
[20:4]
[20:4]Getting published files..
[20:4]	2034776262	34.9 MB	"Kaep Gmod server contents addon #2"
[20:4]	2034758262	598.1 MB	"Kaep Gmod server contents addon #1"
[20:4]Done.
[20:4]
![image](https://user-images.githubusercontent.com/43790127/95898806-e5186e00-0d8f-11eb-89ed-e0d8ef91d72e.png)

**Comment by ApekByz** [comment]
I don't think that if you need anything else, tell me or

**Comment by Leeous** [comment]
@ApekByz is it still just saying loading? That's so weird. I really don't get what's going on here. If you would, expand those Objects in the Chrome log and screenshot again. 🙃

**Comment by Leeous** [comment]
If you're okay with it, could you message me on Twitter or Discord? 

[Twitter](https://twitter.com/LeeTheCoder?s=09)
Discord: **Leeous#4510**
